### ISSUE TITLE
Introduce FAC 9 to Labels!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#11]
@iteles / @shouston3  I might not be there for the start of FAC 9 ... can you please _ensure_ that people see the _team communication_ potential of Labels as _early_ as possible?

It appears that both labels and issues are not used _effectively_ by people who have been on FAC: 
- https://github.com/foundersandcoders/sail-back/issues?q=is%3Aissue
- https://github.com/foundersandcoders/oursite/issues

> not trying to "pick" on anyone, just observed that people don't "_categorise_" issues/stories ... 

Please see: https://www.agilealliance.org/glossary/backlog-grooming/

**Comment by iteles** [comment]
Update this issue for FAC10? 😉 

cc @jsms90 @Cleop @njsfield (does it fit with week 1 curriculum?)

**Comment by jsms90** [comment]
I'm trying to figure it out tbh. There is a _lot_ in terms of process that I would introduce into the course earlier. At this point we're changing quite a lot of content for week 1 already...

In the spirit of curriculum changes being an iterative process, rather than chucking everything out and starting fresh with each cohort, we might be coming close to asking for too much change too quickly if we do much more.

The other thing I would say is that many people will only have used git & github by themselves before. Some of them might not even be used to raising issues at all. I'm an incredibly big fan of introducing process, and introducing best practices as early as possible. But it might be worth introducing labels in week 2 instead? After people have had experience of week 1's project, and getting their head around the git workflow in general?

**Comment by iteles** [comment]
@cleop has a recurring spot at Founders & Coders where she talks through how to run a project, including raising issues and labels 👍
