### ISSUE TITLE
Resync repositories

### ISSUE THREAD

**Issue by SimonLab** [dwyl/labels#116]
The PR #113 record synched repositories and display the list on the main page:

![image](https://user-images.githubusercontent.com/6057298/178362326-a9e337fc-084e-43a2-afc9-d4b67ba70431.png)

We now want to add a `re-sync` button/link to re-sync all the previously sync repositories.

Because this process will take a bit of time (for each label on every repositories, we send a request to the Github api) I'm think of using LiveView to report the status of the sync

related to: #112

**Comment by SimonLab** [comment]
I'm not sure I understand what you mean with https://github.com/dwyl/labels/issues/116#issuecomment-1181591240

The current "sync" button only sync the target repository in the t form.
I can reuse the backend logic and apply it to the list of already synched repositories and for this I want to add another "re-sync" button above the list of repositories.
Do you have another user flow in mind?

**Comment by nelsonic** [comment]
Apologies if that was unclear. Yes, the current button will sync in the manually input form. 
I mean that the _existing_ functionality can be repurposed with relative ease.
e.g. we put a **`<table>`** at the bottom of the page listing the previously synched repos.

Rather than a **`<table>`**, we can _simulate_ a table with [**`display: table`**](https://tailwindcss.com/docs/display#table) (CSS) 
but the actual markup is a **`<form>`** with disabled inputs and a **`re-sync`** button. 

If this is still unclear, apologies, I can probably _build_ it faster than I can explain it. 👨‍💻 💭

**Comment by SimonLab** [comment]
PR for this issue ready #120 
It is also already deployed at https://labels.fly.dev/
Let me know your thought @nelsonic thanks

**Comment by nelsonic** [comment]
@SimonLab looks great! functionality is all there. 🎉 
PR merged. ✅

**Comment by SimonLab** [comment]
#120 deployed and working
