### ISSUE TITLE
BUG: Label Sync doesn't allow sync on org/repo I am owner of ... 🤷‍♂️ 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#155]
Trying to sync labels to: https://github.com/bmhco/shared

![image](https://user-images.githubusercontent.com/194400/203734288-b859f032-f094-40dd-a283-eafd54a9bf21.png)

https://github.com/orgs/bmhco/people/nelsonic
![image](https://user-images.githubusercontent.com/194400/203735419-3285f959-5a67-401e-8579-85681049d567.png)

Video:

https://user-images.githubusercontent.com/194400/203735703-cc6f740b-4e98-4d6b-965c-ee744ff4553f.mov

I've tried logging out/in clearing cache etc. I still cannot sync. 😢

**Comment by nelsonic** [comment]
@SimonLab would you mind taking a quick look at this. 🙏 
(if you need me to remote-debug this with you, we could always get on a Zoom call if you're free ...)

**Comment by SimonLab** [comment]
I'll have a look this evening when I'm back at the desk :+1:

**Comment by nelsonic** [comment]
Merci buckets. 🙏

**Comment by nelsonic** [comment]
@SimonLab any luck investigating this? Did you add any `dbg` statements and deploy? If not, LMK if you want to pair on this at some point tomorrow. Thanks! 👌

**Comment by SimonLab** [comment]
The error is raised in the following function:
https://github.com/dwyl/labels/blob/a3ac7d071272c4fc78769b28f910f26299e522af/lib/labels_web/controllers/page_controller.ex#L128-L156

More specifically at:
https://github.com/dwyl/labels/blob/a3ac7d071272c4fc78769b28f910f26299e522af/lib/labels_web/controllers/page_controller.ex#L151-L153

For each labels on the "source" repository (ie dwyl/labels) the function will send an api request to Github to either create the label or update it if it already exist on the target repository. The api request can fail because the target or source repository is not found (in this case they should be found) or it can be any other http issue while sending the requests.

We can add some `dbg` in the following file:
https://github.com/dwyl/labels/blob/a3ac7d071272c4fc78769b28f910f26299e522af/lib/labels/github/api.ex

We can start by logging the `res` in the function:
https://github.com/dwyl/labels/blob/a3ac7d071272c4fc78769b28f910f26299e522af/lib/labels/github/api.ex#L46-L52
At the moment if the status code is not 200 or 404 the `:error` value is returned. It's possible the Github API has been updated and returns another status code when the labels are created or updated

**Comment by nelsonic** [comment]
Still getting the same error:

![image](https://user-images.githubusercontent.com/194400/206573697-b2f05b5f-843e-4116-937f-ad55f60535c4.png)

Dunno if the `user_agent` update has been deployed to Fly.io 💭 
Happy to remote-pair/debug this with you tomorrow after standup. 👍

**Comment by nelsonic** [comment]
It appears that this is a config issue, not a **`Bug`** ...
had to visit **`Third-party application access policy`**:
https://github.com/organizations/bmhco/settings/oauth_application_policy
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/194400/206671692-e8ab5382-72dc-43d3-9b96-f23d851fb38e.png">

And click **`Remove restrictions`**. 

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/194400/206672004-2d6e620a-9ad5-451c-8ffa-dd522c7cf79c.png">

You should see:

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/194400/206672147-0610faf6-4c78-46dd-9b05-153485f23c30.png">


Then syncing will work. 👍 

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/194400/206672231-a49a4bcd-cb44-4e16-9679-50158b675da2.png">

@SimonLab thanks for your persistence in debugging this. 👍 
Happy to leave the logging in the app for future debugging.

**Comment by nelsonic** [comment]
What is the best way to _document_ this for other people who may face a similar issue in the future? 💭

**Comment by nelsonic** [comment]
I think this is working now. 👌 
Closing. ✅ 
Will re-open if still an issue.
