### ISSUE TITLE
epic label ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#35]
When a "_Story_" is _actually_ a larger collection of features that can/should be sub-divided, the overarching story is referred to as an "_Epic_". see: 
https://www.scrumalliance.org/community/spotlight/mike-cohn/march-2014/agile-user-stories-epics-and-themes 
The _question_ is: how do we _label_ this kind of issue in a GitHub Backlog...?

we needed a way to designate an "Epic" today: https://github.com/o2tank/setup/issues/17#issuecomment-253814070 

@iteles thoughts?

**Comment by nelsonic** [comment]
@iteles / @jrans / @des-des has the use of the `Epic` label for the "ART" project been _successful_? (_does it help to organise the project into related features/themes which are then split out into smaller stories_)

![cmt-issues-with-epic-label](https://cloud.githubusercontent.com/assets/194400/19476025/e7794a44-952e-11e6-96d1-2c30e04b8a7f.png)

**Comment by iteles** [comment]
This hasn't actually been successful but that's mostly because our Product Owner was a little too busy so a lot of these epics were initial placeholders that he never filled in or went back to update so that have become disused.

We use this much more sporadically on OA where as *I* have found them useful personally, but I don't think the developers use them. They will come into play a lot more in the next stage where there are 5 or 6 big topics to tackle.
<img width="617" alt="screen shot 2016-10-18 at 22 05 50" src="https://cloud.githubusercontent.com/assets/4185328/19496390/37fe9eb0-957f-11e6-970f-cd1d1ba13ff0.png">

Thoughts @naazy @Conorc1000 @roryc89 ?

**Comment by des-des** [comment]
@nelsonic I agree with @iteles on art. I think Having a set of top level issues could be useful for a big project though.

**Comment by jrans** [comment]
@nelsonic If done right it can be but its hard to draw a line at whats epic plus no real use to developer as concentrating on smaller issues and more for managing things in longer term. No real use filtering by it too while milestones more helpful.

**Comment by nelsonic** [comment]
Ok. so what I _should_ have asked was: how do we inform a PO that the story they have _just_ written is actually _several_ stories and it should therefore be split out accordingly? :thinking:

**Comment by nelsonic** [comment]
@iteles how do you refer to a "bigger issue" in projects if not as an `epic` ...?

**Comment by iteles** [comment]
Like I said, I use `epic` as a label across the various projects and I've seen two sets of developers use them in the last week (correctly). It's time:
<img width="638" alt="screen shot 2016-11-21 at 10 42 55" src="https://cloud.githubusercontent.com/assets/4185328/20539466/0573f4f2-b0ed-11e6-88f0-d01344134a07.png">

I use a deep deep blue for `epics` because I feel like it gives them some weight and substance without making them depressing (black).

**Comment by iteles** [comment]
https://github.com/dwyl/labels/blame/18039e87ef897d40f85454735f320828ac11331c/README.md#L73

**Comment by Cleop** [comment]
@iteles - now that this label has been made can we close this issue?

**Comment by iteles** [comment]
:+1:
