### ISSUE TITLE
Is it bad to use 'question', 'help wanted' and 'discuss' labels together?

### ISSUE THREAD

**Issue by Cleop** [dwyl/labels#60]
I keep finding myself using the 'question',  'help wanted' and 'discuss' labels together on issues. I'm not sure if it's label over-kill and wondered if I'm somehow missing the distinctions between their purposes:

``` help-wanted #128A0C - looking for help or expertise on a subject ```
``` question #CC317C - for open questions ```
``` discuss #60EEEE - invites discussion from contributors ```

E.g.
https://github.com/research-resource/research_resource/issues/51

The logic behind my use of them is to apply them when... an issue needs input from others (help-wanted) and I'm not sure of the right/wrong answer (question /discuss).

What do others think?

**Comment by nelsonic** [comment]
@Cleop there's nothing "_wrong_" with using _multiple_ labels. 
labels are a great way to _categorize_ information and when we get our "_One View_" across all projects and we can request help from _anyone_ in our community the `question` label is a _useful_ piece of info that indicates that someone has something they would like an _answer_ to and might not take very long ... 
`discuss` is _useful_ because the `question` might be a good place to discuss more than one answer/option. 
Your logic is _flawless_. `continue`. ❤️  ✅

**Comment by Cleop** [comment]
Thanks @nelsonic for sharing your perspective.
